name: Auto Tag

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Create Tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important: This is needed to fetch all tags

      - name: Bump version and push tag
        id: create_tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: main

      - name: Check out new tag
        run: |
          echo "New tag created: ${{ steps.create_tag.outputs.tag }}"

      - name: Save the tag
        run: |
          echo "${{ steps.create_tag.outputs.tag }}" > tag.txt    

      - name: Upload tag as artifact
        uses: actions/upload-artifact@v2
        with:
          name: tag
          path: tag.txt